"""Rule-based Oostfräisk-to-Gronings transliteration."""

from __future__ import annotations

REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ('óóii', 'óó-ii'),
    ('óóee', 'óó-ee'),
    ('óóa', 'óó-a'),
    ('beee', 'be-ee'),
    ('biii', 'bii-i'),
    ('iiu', 'bii-u'),
    ('iie', 'ii-e'),
    ('uuu', 'u-uu'),
    ('ou', 'o-u'),
    ('eu', 'e-u'),
    ('ei', 'ij'),

    ('ienst', 'inste'),
    ('ient', 'inte'),
    ('ien', 'inne'),
    ('iepst', 'ipste'),
    ('iept', 'ipte'),
    ('iep', 'ippe'),
    ('ietst', 'itste'),
    ('iets', 'itse'),
    ('iet', 'itte'),
    ('iekst', 'ikste'),
    ('ieks', 'ikse'),
    ('iek', 'ikke'),
    ('iechtst', 'ichtste'),
    ('iechst', 'ichste'),
    ('iecht', 'ichte'),
    ('iebst', 'ibste'),
    ('ieb', 'ibbe'),
    ('iedst', 'idste'),
    ('ied', 'idde'),
    ('iefst', 'ifste'),
    ('ieft', 'ifte'),
    ('ief', 'iffe'),
    ('iev', 'ive'),
    ('ielp', 'ilpe'), # only wielp and tielpoest
    ('ilpeo', 'illepo'), # fix only the word tielpoest
    ('ielt', 'ilte'),
    ('iltea', 'illeta'), # fix only the word stieltau
    ('iele', 'ìlle'),
    ('ield', 'ìld'),
    ('iel', 'ille'),
    ('iest', 'iste'),
    ('iesk', 'ìsk'), # only 3 proper names
    ('iesde', 'ìsde'), # could clash with compounds where second part starts with de, but there are none.
    ('iesen', 'ìzzen'),
    ('ieser', 'ìzzer'),
    ('ies', 'izze-'),

    ('îiv', 'ieve'),
    ('îin', 'iene'),
    ('îik', 'ieke'),
    ('îiğ', 'ieğe'),

    ('îits', 'ietse'),
    ('îitk', 'ietke'),
    ('îit', 'iete'),
    ('îist', 'ieste'),
    ('îis', 'ieze'),
    ('îidst', 'iedste'),
    ('îid', 'iede'),
    ('îift', 'iefte'),
    ('îif', 'iefe'),
    ('îimk', 'iemke'),
    ('îim', 'ieme'),
    ('îil', 'iele'),
    ('îibk', 'iebke'),
    ('îib', 'iebe'),
    ('îirn', 'ierne'),
    ('îir', 'iere'),
    ('îipt', 'iepte'),
    ('îipk', 'iepke'),
    ('îip', 'iepe'),

    ('äenst', 'enste'),
    ('äent', 'ente'),
    ('äen', 'enne'),
    ('äepst', 'epste'),
    ('äept', 'epte'),
    ('äep', 'eppe'),
    ('äetst', 'etste'),
    ('äets', 'etse'),
    ('äet', 'ette'),
    ('äekst', 'ekste'),
    ('äeks', 'ekse'),
    ('äek', 'ekke'),
    ('äechtst', 'echtste'),
    ('äechst', 'echste'),
    ('äecht', 'echte'),
    ('äebst', 'ebste'),
    ('äeb', 'ebbe'),
    ('äedst', 'edste'),
    ('äed', 'edde'),
    ('äest', 'este'),
    ('läesb', 'lèsbe'), # single word
    ('mäesk', 'mèske'), # single word
    ('äese', 'èzze'),
    ('äes', 'ezze'),
    ('äecht', 'echte'),
    ('äept', 'epte'),
    ('äep', 'eppe'),
    ('äelfd', 'elfde'),
    ('äelft', 'elfte'),
    ('äelv', 'elve'),
    ('äel', 'elle'),
    ('äeng', 'enge'),
    ('äeğt', 'ègd'),
    ('äeğts', 'ègds'),
    ('äeğst', 'ègst'),

    ('óóenst', 'oanste'),
    ('óóent', 'oante'),
    ('óóen', 'oane'),
    ('óóepst', 'oapste'),
    ('óóept', 'oapte'),
    ('óóep', 'oape'),
    ('óóetst', 'oatste'),
    ('óóets', 'oatse'),
    ('óóet', 'oate'),
    ('óóekst', 'oakste'),
    ('óóeks', 'oakse'),
    ('óóek', 'oake'),
    ('óóechtst', 'oachtste'),
    ('óóechst', 'oachste'),
    ('óóecht', 'oachte'),
    ('óóebst', 'oabste'),
    ('óóeb', 'oabe'),
    ('óóedst', 'oadste'),
    ('óóed', 'oade'),
    ('óóeğ', 'oage'),
    ('óóeğt', 'oagte'),

    ('oenst', 'onste'),
    ('oent', 'onte'),
    ('oen', 'onne'),
    ('oepst', 'opste'),
    ('oept', 'opte'),
    ('oep', 'oppe'),
    ('oetst', 'otste'),
    ('oets', 'otse'),
    ('oet', 'otte'),
    ('oekst', 'okste'),
    ('oeks', 'okse'),
    ('oek', 'okke'),
    ('oechtst', 'ochtste'),
    ('oechst', 'ochste'),
    ('oecht', 'ochte'),
    ('oebst', 'obste'),
    ('oeb', 'obbe'),
    ('oedst', 'odste'),
    ('oed', 'odde'),
    ('oelk', 'olke'),
    ('oelst', 'olste'),
    ('oelm', 'olme'), # Folme, Folmo
    ('oelv', 'olve'), # koelv - Kolbe
    ('oele', 'awle'), # troeler - Trawler
    ('oelğ', 'olge'), # only foelğ
    ('oelt', 'olte'),
    ('oel', 'olle'),

    ('ieğst', 'igste'),
    ('ieğt', 'igte'),
    ('ieğ', 'igge'),

    ('ûulst', 'uulste'),
    ('ûul', 'uule'),
    ('ûurt', 'uurte'),
    ('ûurd', 'uurde'),
    ('ûur', 'uure'),
    ('ûur', 'uure'),
    ('ûunt', 'uunte'),
    ('ûun', 'uune'),

    ('ûuğst', 'uugste'),
    ('ûuğt', 'uugte'),
    ('ûuğ', 'uuge'),
    ('ûudst', 'uudste'),
    ('ûud', 'uudde'),
    ('ûuvst', 'uuvste'),
    ('ûuv', 'uuvve'),
    ('ûumst', 'uumste'),
    ('ûum', 'uumme'),
    ('ûupst', 'uupste'),
    ('ûup', 'uuppe'),
    ('ûufst', 'uufste'),
    ('ûuf', 'uufe'),
    ('ûust', 'uuste'),
    ('ûus', 'uuse'),
    ('ûutst', 'uutste'),
    ('ûuts', 'uutse'),
    ('ûut', 'uutte'),
    ('ûukst', 'uukste'),
    ('ûuks', 'uukse'),
    ('ûuk', 'uukke'),

    ('âald', 'aalde'),
    ('âalt', 'aalte'),
    ('âals', 'aalze'),
    ('âalm', 'aalme'),
    ('âalfd', 'aalfde'),
    ('âalft', 'aalfte'),
    ('âalf', 'aalfe'),
    ('âalv', 'aalve'),
    ('âalk', 'aalke'),
    ('âalğ', 'aalge'),
    ('âalb', 'aalbe'),
    ('âal', 'aale'),
    ('âajts', 'aajtse'),
    ('âajtk', 'aajtke'),
    ('âajt', 'aajte'),
    ('âajds', 'aajdes'),
    ('âajd', 'aajde'),
    ('âajnst', 'aajnste'),
    ('âajnt', 'aajnte'),
    ('âajn', 'aajne'),
    ('âajk', 'aajke'),
    ('âajst', 'aajste'),
    ('âajsk', 'aajske'),
    ('âajs', 'aajze'),
    ('âajğ', 'aajge'),
    ('âajv', 'aajve'),
    ('âajp', 'aajpe'),
    ('âajl', 'aajle'),
    ('âaj', 'aaje'),

    ('âarmst', 'aarmste'),
    ('âarmt', 'aarmte'),
    ('âarm', 'aarme'),
    ('âarkst', 'aarkste'),
    ('âarkt', 'aarkte'),
    ('âark', 'aarke'),
    ('âarft', 'aarfte'),
    ('âarst', 'aarste'),
    ('âars', 'aarze'),
    ('âarğt', 'aargte'),
    ('âarğ', 'aarge'),
    ('âart', 'aarte'),
    ('âarvt', 'aarvte'),
    ('âarv', 'aarve'),
    ('âarnt', 'aarnte'),
    ('âarnk', 'aarnke'),
    ('âarn', 'aarne'),
    ('âarl', 'aarle'),
    ('âardst', 'aardste'),
    ('âard', 'aarde'),
    ('âarpst', 'aarpste'),
    ('âarp', 'aarpe'),
    ('âarw', 'aarve'), # only lâarw - Larve
    ('âarb', 'aarbe'),
    ('âar', 'aare'),

    ('âanst', 'aanste'),
    ('âans', 'aanze'),
    ('âankst', 'aankste'),
    ('âankt', 'aankte'),
    ('âank', 'aanke'),
    ('âangt', 'aangte'),
    ('âangst', 'aangste'),
    ('âang', 'aange'),
    ('âant', 'aante'),
    ('âan', 'aane'),

    ('âacht', 'aachte'),
    ('âaf', 'aafe'),
    ('âakst', 'aakste'),
    ('âaks', 'aakze'),
    ('âakt', 'aakte'),
    ('âamp', 'aampe'),
    ('âamt', 'aamte'),
    ('âams', 'aamze'),
    ('âamk', 'aamke'),
    ('âam', 'aame'),
    ('âak', 'aake'),
    ('âatst', 'aatste'),
    ('âats', 'aatse'),
    ('âasp', 'aaspe'),
    ('âast', 'aaste'),
    ('âask', 'aaske'),
    ('âas', 'aaze'),
    ('âağt', 'aagte'),
    ('âağ', 'aage'),
    ('âapst', 'aapste'),
    ('âaps', 'aapze'),
    ('âap', 'aape'),
    ('âab', 'aabe'),
    ('âadk', 'aadke'),
    ('âad', 'aade'),
    ('âat', 'aate'),
    ('âag', 'aage'),

    ('ôort', 'oorte'),
    ('ôor', 'oore'),
    ('ôotst', 'ootste'),
    ('ôot', 'oote'),
    ('ôods', 'oodse'),
    ('ôod', 'oode'),
    ('ôos', 'ooze'),
    ('ôomt', 'oomte'),
    ('ôom', 'oome'),
    ('ôog', 'ooge'), # this shouldn't exist I think
    ('ôoğst', 'oogste'),
    ('ôoğ', 'ooge'),
    ('ôopt', 'oopte'),
    ('ôop', 'oope'),
    ('ôovst', 'oovste'),
    ('ôovt', 'oovte'),
    ('ôov', 'oove'),
    ('ôols', 'oolze'),
    ('ôolk', 'oolke'),
    ('ôol', 'oole'),
    ('ôonst', 'oonste'),
    ('ôont', 'oonte'),
    ('ôonk', 'oonke'),
    ('ôon', 'oone'),
            
    ('ôojst', 'oojste'),
    ('ôojs', 'oojze'),
    ('ôojd', 'oojde'),
    ('ôojk', 'oojke'),
    ('ôojl', 'oojle'),
    ('ôojt', 'oojte'),
    ('ôoj', 'ooje'),
    ('ôof', 'oofe'),
    ('ôok', 'ooke'),
    ('ôo', 'o-e'),

    ('êerst', 'eerste'),
    ('êers', 'eerze'),
    ('êerd', 'eerde'),
    ('êerk', 'eerke'),
    ('êert', 'eerte'),
    ('êernt', 'eernte'),
    ('êern', 'eerne'),
    ('êer', 'eere'),
    ('êev', 'eeve'),
            
    ('êelt', 'eelte'),
    ('êeld', 'eelde'),
    ('êel', 'eele'),

    ('êeks', 'eekze'),
    ('êek', 'eeke'),
    ('êem', 'eeme'),
    ('êes', 'eeze'),
    ('êen', 'eene'),
    ('êeğst', 'eegste'),
    ('êeğt', 'eegte'),
    ('êeğ', 'eege'),
    ('êets', 'eetze'),
    ('êet', 'eete'),
    ('êed', 'eede'),
    ('êep', 'eepe'),
    ('êeg', 'eege'), # probably small errors that should be ğ
    ('êe', 'ee'), # only the exclamation hêe
            
    ('üelst', 'ülste'),
    ('üelt', 'ülte'),
    ('üekst', 'ükste'),
    ('üekst', 'ükste'),
    ('üekt', 'ükte'),
    ('üek', 'ükke'),
    ('üeğ', 'ügge'),
    ('üets', 'ütse'),
    ('üet', 'ütte'),
    ('üed', 'üdde'),
    ('üemt', 'ümte'),
    ('üelp', 'ülpe'),
    ('üerd', 'ürde'),
    ('üeg', 'ügge-'),
    ('üeger', 'ügger'),

    ('üen', 'ünne'),
    ('üer', 'ürre'),
    ('ües', 'üzze'),

    ('öest', 'öste'),
    ('öesk', 'öske'),
    ('öes', 'özze'),
    ('öetk', 'ötke'),
    ('öets', 'ötse'),
    ('öet', 'ötte'),
    ('öertst', 'örtste'),
    ('öerst', 'örste'),
    ('öers', 'örse'),
    ('öerk', 'örke'),
    ('öerd', 'örde'),
    ('öerğ', 'örğe'),
    ('öer', 'örre'),
    ('öeds', 'ödse'),
    ('öed', 'öde'),

    ('öeğt', 'öğte'),
    ('öeğ', 'ögge'),

    ('ueps', 'upse'),
    ('uep', 'uppe'),
    ('ueks', 'ukse'),
    ('uek', 'ukke'),
    ('uemp', 'umpe'),
    ('uem', '[UMME]'),

    ('uu', 'oe'),
    ('au', '\uE000'),
    ('ur', 'oer'),
    ('uer', 'oer'),
    ('óó', 'oa'),
    ('ó', 'oa'), # Gronings has no special way to write the unstressed oa?
    ('u', 'ó'),
    ('ü', 'u'),

    ('â\uE000kst', 'oukste'),
    ('â\uE000k', 'ouke'),
    ('â\uE000l', 'oule'),
    ('â\uE000d', 'oude'),
    ('â\uE000st', 'ouste'),
    ('â\uE000s', 'ouze'),
    ('â\uE000t', 'oute'),
    ('â\uE000ns', 'ounze'),
    ('â\uE000nt', 'ounte'),
    ('â\uE000n', 'oune'),
    ('â\uE000ğt', 'ougte'),
    ('â\uE000ğ', 'ouge'),
    ('â\uE000p', 'oupe'),
    ('â\uE000v', 'ouve'),
    ('â\uE000r', 'ouer'),
    ('â\uE000w', 'aauwe'), # only 4 words
    ('â\uE000', 'aauwe'),

    ('a\uE000', 'aauw'),
    ('\uE000', 'ou'),

    ('öyet', 'uite'),
    ('öyeğ', 'euge'),
    ('öyemt', 'uimte'),
    ('öyem', 'uime'),
    ('öyevt', 'uivte'),
    ('öyev', 'uive'),
    ('öyest', 'uiste'),
    ('öyes', 'euze'),
    ('öyent', 'uinte'),
    ('öyen', 'uine'),
    ('öyelt', 'uilte'),
    ('öyel', 'uile'),

    ('öyed', 'uide'), # only höyed
    ('öyeps', 'eupze'), # only röyeps
    ('öyep', 'uipe'),
    ('öyek', 'uike'), # söyek and öyek
    ('öyef', 'uive'), # only dröyef

    ('öy', 'ui'), # imperfect, sometimes should be eu
    ('öö', 'eu'),

    ('ääe', 'ije'),
    ('äej', 'ije'),
    ('äj', 'ij'),
    ('ai', 'aai'),
    ('aaj', 'aai'),
    ('äär', 'aaier'),
    ('ää', 'èè'),
    ('äi', 'ai'),
    ('óó', 'oa'),
    ('ii', 'ie'),

    ('wj', 'vi'),
    ("h'", 'e'),
    ("s'", 'ze'),
    ("t't", 't'),
    ("'t", 't'),
    ("t'", 'te'),
    ("w'", 'we'),
    ("d'r", 'der'),
    (" d' ", ' de '),
    ("'k", 'k'),
    ("'n", 'n'),

    ('âl', 'aal'),
    ("f'r", 'veur'),
    ("dai ", 'dij '),
    ("doo ", 'dou '),
    (" ón ", ' en '),
            
    # ('ğ', 'g'), # maybe first iğ -> eg and then the rest of the ğ to g?
    (' f', ' v'),
    ('"f', '"v'),
    (' s', ' z'),
    (' zl', ' sl'),
    (' zt', ' st'),
    (' zp', ' sp'),
    (' zk', ' sk'),
    (' zn', ' sn'),
    (' zm', ' sm'),
    (' zw', ' sw'),
)


def transliterate(text: str) -> str:
    """Apply the hardcoded rules to an input string."""
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    return text

if __name__ == '__main__':
    import sys

    for line in sys.stdin:
        print(transliterate(line.strip()))
